name: AccuKnox IaC Scan Workflow

on:
  push:
    branches:
      - iac
  pull_request:

jobs:
  iac_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: AccuKnox IaC Scan
        uses: accuknox/iac-scan-action@latest
        with:
          directory: ./
          output_file_path: ./results
          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          accuknox_endpoint: "cspm.demo.accuknox.com"
          accuknox_label: ${{ secrets.ACCUKNOX_LABEL }}
          quiet: "true"
          soft_fail: true
